// Generated by CoffeeScript 1.8.0
(function() {
  var app, baseUrl;

  baseUrl = 'https://staging.remontnik.ru/';

  app = angular.module('RemontnikApp', ['ngResource']);

  app.factory('Portfolio', function($resource) {
    return $resource(baseUrl.concat('api/v1/portfolio/all'));
  });

  app.controller('PortfolioController', function($scope, Portfolio) {
    Portfolio.get(function(data) {
      return $scope.portfolioItems = data.results;
    });
    return $scope.getAbsolutePath = function(relativePath) {
      return baseUrl.concat(relativePath);
    };
  });

}).call(this);
